airflow:
  connections:
    - conn_id: indec
      conn_type: http
      conn_host: https://www.indec.gob.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: estadisticacordoba
      conn_type: http
      conn_host: https://datosestadistica.cba.gov.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: recaudacion
      conn_type: http
      conn_host: https://contenidos.afip.gob.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: emae
      conn_type: http
      conn_host: https://www.indec.gob.ar/ftp/cuadros/economia/
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: