airflow:
  connections:
    - conn_id: indec
      conn_type: http
      conn_host: https://www.indec.gob.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: estadisticacordoba
      conn_type: http
      conn_host: https://datosestadistica.cba.gov.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: recaudacion-arca
      conn_type: http
      conn_host: https://contenidos.afip.gob.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
    - conn_id: emae
      conn_type: http
      conn_host: https://www.indec.gob.ar/ftp/cuadros/economia/
    - conn_id: ipc-tucuman
      conn_type: http
      conn_host: https://estadistica.tucuman.gov.ar
    - conn_id: ipc-santafe
      conn_type: http
      conn_host: https://www.estadisticasantafe.gob.ar
    - conn_id: ipc-mendoza
      conn_type: http
      conn_host: https://deie.mendoza.gov.ar
    - conn_id: ipc-gba
      conn_type: http
      conn_host: https://infra.datos.gob.ar
    - conn_id: balanza-comercial
      conn_type: http
      conn_host: https://www.indec.gob.ar
    - conn_id: dolar-blue
      conn_type: http
      conn_host: https://dolarhoy.com
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: