airflow:
  connections:
    - conn_id: indec
      conn_type: http
      conn_host: https://www.indec.gob.ar
      conn_schema:
      conn_login:
      conn_password:
      conn_port:
      conn_extra:
        example_extra_field: example-value
  pools:
    - pool_name:
      pool_slot:
      pool_description:
  variables:
    - variable_name:
      variable_value: